kind: pipeline
name: bopflow

platform:
  os: linux
  arch: amd64

steps:
- name: pypi_publish
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
